"""
Shulchan Aruch Two-Page Layout Generator

Given Hebrew texts for a siman and its commentaries, generates a 2-page
LuaLaTeX document:
  Page 1: Mechaber + Rema (center) with 2 main commentaries flanking,
          all in interlinear Hebrew+Translation format.
  Page 2: (TODO) Secondary commentaries + side panels.

Usage:
    uv run sa_generator.py
"""

import subprocess
import os
from pathlib import Path
from dataclasses import dataclass, field


LOREM_EN = (
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
    "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
    "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris "
    "nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in "
    "reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
)

LOREM_EN_SHORT = (
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, "
    "sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
)


@dataclass
class Commentary:
    """A single commentary text block."""
    name_he: str
    name_en: str
    # List of seif-katan dicts: {"he": str, "en": str}
    seifim_ketanim: list = field(default_factory=list)


@dataclass
class SeifData:
    """A single seif of the Mechaber."""
    mechaber_he: str
    mechaber_en: str  # translation (or lorem)
    rema_he: str = ""
    rema_en: str = ""


@dataclass
class SimanData:
    """All texts for a single siman of SA."""
    chelek_he: str           # e.g. "אורח חיים"
    chelek_en: str           # e.g. "Orach Chaim"
    siman_num_he: str        # e.g. 'ר"צ'
    siman_num_en: str        # e.g. "290"
    topic_he: str            # e.g. "הלכות שבת"
    topic_en: str            # e.g. "Laws of Shabbos"
    daf_he: str              # e.g. 'קנ"ט'

    seifim: list[SeifData] = field(default_factory=list)

    # Page 1: the 2 main commentaries flanking the mechaber
    comm_left: Commentary = None   # e.g. Magen Avraham
    comm_right: Commentary = None  # e.g. Taz / Magen David


# ═══════════════════════════════════════════
#  LaTeX generation
# ═══════════════════════════════════════════

def escape_latex(text: str) -> str:
    """Escape special LaTeX characters."""
    text = text.replace("&", r"\&")
    text = text.replace("#", r"\#")
    text = text.replace("$", r"\$")
    text = text.replace("_", r"\_")
    return text


HEB_LETTERS = "אבגדהוזחטיכלמנסעפצקרשת"

def to_heb_letter(n: int) -> str:
    if 1 <= n <= len(HEB_LETTERS):
        return HEB_LETTERS[n - 1]
    return str(n)


def gen_preamble() -> str:
    return r"""% Auto-generated by sa_generator.py
% Compile with: lualatex sa_output.tex
\documentclass[11pt,letterpaper,openany]{scrbook}

\usepackage[letterpaper,
  bindingoffset=0.2in,
  left=0.45in, right=0.45in,
  top=0.4in, bottom=0.4in,
  footskip=0.2in, marginparwidth=0em
]{geometry}

\usepackage{fontspec}
\usepackage{polyglossia}
\usepackage{xcolor}
\usepackage{ragged2e}
\usepackage{titlesec}
\usepackage{microtype}

\setmainlanguage{english}
\setotherlanguage{hebrew}

% ── Colors ──
\definecolor{hcolor}{HTML}{1A3264}
\definecolor{ruleGrey}{HTML}{AAAAAA}
\definecolor{lightGrey}{HTML}{E0E0E0}

% ── Fonts ──
\newfontfamily\hebrewfont[
  Path=../Fonts/, Script=Hebrew, Ligatures=TeX,
  BoldFont=FrankRuehlCLM-Bold.otf
]{FrankRuehlCLM-Medium.otf}

\newfontfamily\mechaberfont[
  Path=../Fonts/Frank/static/, Script=Hebrew, Ligatures=TeX,
  BoldFont=FrankRuhlLibre-Bold.ttf
]{FrankRuhlLibre-Regular.ttf}

\newfontfamily\commentaryfont[
  Path=../Fonts/, Script=Hebrew, Ligatures=TeX,
  BoldFont=FrankRuehlCLM-Bold.otf
]{FrankRuehlCLM-Medium.otf}

\newfontfamily\engfont[
  Path=../Fonts/, Ligatures=TeX,
  BoldFont=EBGaramond-Bold.ttf,
  ItalicFont=EBGaramond-Italic.ttf
]{EBGaramond-Regular.ttf}

% ── Spacing ──
\setlength\parindent{0pt}
\setlength{\columnsep}{1em}
\raggedbottom
\pagestyle{empty}

% ── Interlinear macros ──
% Hebrew catchword followed by em-dash, then translation follows inline
\newcommand{\Heb}[1]{\texthebrew{\textbf{#1}}~--- }
% Seif marker: just the Hebrew letter, large and bold
\newcommand{\Seif}[1]{{\Large\bfseries\texthebrew{#1}}\ }
% Rema marker
\newcommand{\Rema}{\texthebrew{\textbf{הגה:}}\ }
% Commentary header
\newcommand{\CommHeader}[1]{%
  \par\noindent{\commentaryfont\fontsize{9}{11}\selectfont%
  \textcolor{hcolor}{\texthebrew{\textbf{#1}}}}\par\smallskip
}
% Seif katan marker in commentary
\newcommand{\SK}[1]{{\bfseries\texthebrew{#1}}\ }
% Thin rule
\newcommand{\thinrule}{\par\noindent\textcolor{ruleGrey}{\rule{\linewidth}{0.3pt}}\par\vspace{2pt}}

\begin{document}
\begin{sloppypar}
"""


def gen_page1(data: SimanData) -> str:
    """Generate page 1: header + 3-column interlinear layout."""
    lines = []

    # ── Header bar ──
    lines.append(r"""
%% ━━━━ PAGE 1 ━━━━
%% Header
\noindent
\colorbox{lightGrey}{\parbox{\dimexpr\textwidth-8pt\relax}{%
  \centering\vspace{3pt}%
  \begin{hebrew}%
  {\mechaberfont\fontsize{11}{13}\selectfont%
  \textcolor{hcolor}{%
""")
    lines.append(
        f"שולחן ערוך {data.chelek_he}"
        r" \quad "
        f"{data.topic_he}"
        r" \quad "
        f"סימן {data.siman_num_he}"
        r" \quad "
        f"דף {data.daf_he}"
    )
    lines.append(r"""}}%
  \end{hebrew}%
  \vspace{3pt}%
}}

\vspace{6pt}
""")

    # ── 3-column layout ──
    lines.append(r"""
%% 3-column layout: Left comm | Center Mechaber | Right comm
\noindent
%% LEFT: Magen Avraham
\begin{minipage}[t]{0.235\textwidth}
\raggedright
""")

    # Left commentary content (interlinear)
    if data.comm_left:
        lines.append(r"\CommHeader{" + data.comm_left.name_he + "}")
        lines.append(r"{\commentaryfont\fontsize{8.5}{11}\selectfont")
        for sk in data.comm_left.seifim_ketanim:
            he = escape_latex(sk["he"])
            en = sk.get("en", LOREM_EN_SHORT)
            # Hebrew catchword + translation inline
            lines.append(r"\Heb{" + he + "}")
            lines.append(r"}")  # close commentaryfont
            lines.append(r"{\engfont\fontsize{8}{10}\selectfont " + en + r"}")
            lines.append(r"\par\smallskip")
            lines.append(r"{\commentaryfont\fontsize{8.5}{11}\selectfont")
        lines.append(r"}")  # close commentaryfont

    lines.append(r"""
\end{minipage}%
\hfill
%% CENTER: Mechaber + Rema
\begin{minipage}[t]{0.47\textwidth}
""")

    # Center: Mechaber seifim with interlinear translation
    lines.append(r"{\mechaberfont\fontsize{12}{15.5}\selectfont")
    for i, seif in enumerate(data.seifim):
        letter = to_heb_letter(i + 1)

        # Seif marker + Hebrew mechaber text
        lines.append(r"\Seif{" + letter + "}")
        lines.append(r"\Heb{" + escape_latex(seif.mechaber_he) + "}")
        lines.append(r"}")  # close mechaberfont temporarily for English
        lines.append(r"{\engfont\fontsize{10}{13}\selectfont " + seif.mechaber_en + r"}")
        lines.append(r"\par\medskip")

        # Rema if present
        if seif.rema_he:
            lines.append(r"{\mechaberfont\fontsize{12}{15.5}\selectfont")
            lines.append(r"\Rema")
            lines.append(r"\Heb{" + escape_latex(seif.rema_he) + "}")
            lines.append(r"}")  # close mechaberfont
            lines.append(r"{\engfont\fontsize{10}{13}\selectfont " + seif.rema_en + r"}")
            lines.append(r"\par\medskip")

        # Re-open mechaberfont for next seif
        if i < len(data.seifim) - 1:
            lines.append(r"{\mechaberfont\fontsize{12}{15.5}\selectfont")

    lines.append(r"""
\end{minipage}%
\hfill
%% RIGHT: Taz / Magen David
\begin{minipage}[t]{0.235\textwidth}
\raggedright
""")

    # Right commentary content (interlinear)
    if data.comm_right:
        lines.append(r"\CommHeader{" + data.comm_right.name_he + "}")
        lines.append(r"{\commentaryfont\fontsize{8.5}{11}\selectfont")
        for sk in data.comm_right.seifim_ketanim:
            he = escape_latex(sk["he"])
            en = sk.get("en", LOREM_EN_SHORT)
            lines.append(r"\Heb{" + he + "}")
            lines.append(r"}")
            lines.append(r"{\engfont\fontsize{8}{10}\selectfont " + en + r"}")
            lines.append(r"\par\smallskip")
            lines.append(r"{\commentaryfont\fontsize{8.5}{11}\selectfont")
        lines.append(r"}")

    lines.append(r"""
\end{minipage}
""")

    return "\n".join(lines)


def gen_page2_placeholder() -> str:
    """Placeholder page 2 — to be built next."""
    return r"""
\newpage
\begin{center}
{\engfont\Large\textcolor{hcolor}{Page 2 --- Commentary Translations (TODO)}}
\end{center}
"""


def gen_postamble() -> str:
    return r"""
\end{sloppypar}
\end{document}
"""


def generate_tex(data: SimanData) -> str:
    return gen_preamble() + gen_page1(data) + gen_page2_placeholder() + gen_postamble()


def compile_pdf(tex_path: str):
    output_dir = os.path.dirname(tex_path) or "."
    result = subprocess.run(
        ["lualatex", "-interaction=nonstopmode",
         "-output-directory", output_dir, tex_path],
        capture_output=True, timeout=120
    )
    pdf_path = tex_path.replace(".tex", ".pdf")
    if os.path.exists(pdf_path):
        print(f"PDF generated: {pdf_path}")
    else:
        print(f"PDF generation FAILED")
        stderr = result.stderr.decode("utf-8", errors="replace")
        print(stderr[:2000])


# ═══════════════════════════════════════════
#  Sample data: OC 290
# ═══════════════════════════════════════════

def get_sample_data() -> SimanData:
    return SimanData(
        chelek_he="אורח חיים",
        chelek_en="Orach Chaim",
        siman_num_he='ר"צ',
        siman_num_en="290",
        topic_he="הלכות שבת",
        topic_en="Laws of Shabbos",
        daf_he='קנ"ט',

        seifim=[
            SeifData(
                mechaber_he=(
                    'ירבה פירות ומגדים ומיני ריח '
                    'כדי להשלים מנין מאה ברכות:'
                ),
                mechaber_en=(
                    "One should increase [consumption of] fruits, delicacies, "
                    "and fragrant spices in order to complete the count of "
                    "one hundred blessings."
                ),
                rema_he=(
                    'ואם רגיל בשינת צהרים אל יבטלנו '
                    'כי עונג הוא לו (טור):'
                ),
                rema_en=(
                    "And if one is accustomed to an afternoon nap, "
                    "he should not forgo it, for it is a delight for him (Tur)."
                ),
            ),
            SeifData(
                mechaber_he=(
                    'אחר סעודת שחרית קובעים מדרש '
                    'לקרות בנביאים ולדרוש בדברי אגדה '
                    'ואסור לקבוע סעודה באותה שעה:'
                ),
                mechaber_en=(
                    "After the morning meal, one establishes a study session "
                    "to read from the Prophets and to expound on Aggadic "
                    "teachings. It is forbidden to schedule a meal during "
                    "that time."
                ),
                rema_he=(
                    'ופועלים ובעלי בתים שאינן עוסקים בתורה כל ימי שבוע '
                    'יעסקו יותר בתורה בשבת מתלמידי חכמים העוסקים בתורה '
                    'כל ימי השבוע ותלמידי חכמים ימשיכו יותר בעונג אכילה '
                    'ושתיה קצת שהרי מתענגים בלמודם כל ימי השבוע '
                    '[ב"י סי\' רפ"ח בשם ירושלמי]:'
                ),
                rema_en=(
                    "Workers and householders who do not engage in Torah "
                    "study during the weekdays should study more Torah on "
                    "Shabbos than Torah scholars who study all week. "
                    "And Torah scholars should indulge somewhat more in "
                    "the pleasure of eating and drinking, since they already "
                    "derive pleasure from their studies throughout the week "
                    "[Beis Yosef, Siman 288, citing the Yerushalmi]."
                ),
            ),
        ],

        # LEFT: Magen Avraham
        comm_left=Commentary(
            name_he="מגן אברהם",
            name_en="Magen Avraham",
            seifim_ketanim=[
                {
                    "he": (
                        'אין להניח הדרשה עבור סעודה ג\' '
                        'כדאי\' במד\' משלי בפ\' אשת חיל '
                        'שמתו בניו של ר"מ מאותו החטא [רוקח]'
                    ),
                    "en": (
                        "One should not forgo the public Torah discourse "
                        "in favor of the third meal, as we find in the "
                        "Midrash on Mishlei, Parshas Eishes Chayil, that "
                        "the sons of Rabbi Meir died because of this sin "
                        "[Rokeach]."
                    ),
                },
                {
                    "he": (
                        'וצ"ל שהדרשה תהא להורות '
                        'לעם את חקי האלהים ואת תורותיו '
                        'ולהכניס יראת שמים בלבבם '
                        'ולא כמו שנוהגין עכשיו'
                    ),
                    "en": (
                        "And one must say that the discourse should be "
                        "to instruct the people in the statutes of God "
                        "and His laws, and to instill the fear of Heaven "
                        "in their hearts --- and not as is the practice nowadays."
                    ),
                },
                {
                    "he": (
                        'לא יאמר בשבת נישן כדי לעשות '
                        'מלאכתינו בערב [ס"ח סימן רס"ו]'
                    ),
                    "en": (
                        "One should not say on Shabbos, 'Let us sleep so "
                        "that we can do our work in the evening' "
                        "[Sefer Chassidim, siman 266]."
                    ),
                },
            ],
        ),

        # RIGHT: Taz / Magen David
        comm_right=Commentary(
            name_he="מגן דוד",
            name_en="Magen David",
            seifim_ketanim=[
                {
                    "he": (
                        'ירבה פירות ומגדים. '
                        'הנה ידוע כי מספר מאה ברכות '
                        'הוא תקנת דוד המלך עליו השלום '
                        'כמבואר בגמרא מנחות דף מ"ג ע"ב'
                    ),
                    "en": (
                        "One should increase fruits and delicacies. "
                        "It is well known that the count of one hundred "
                        "blessings was enacted by King David, peace be upon "
                        "him, as explained in the Gemara, Menachos 43b."
                    ),
                },
                {
                    "he": (
                        'ובשבת שחסרים כמה ברכות מתפילת '
                        'שמונה עשרה שמתפללים רק שבע ברכות '
                        'ישלים אותם ע"י ברכות הנהנין על פירות '
                        'ובשמים ומיני מגדים'
                    ),
                    "en": (
                        "And on Shabbos, when several blessings are missing "
                        "from the Shemoneh Esrei --- for one recites only "
                        "seven blessings --- one should complete them through "
                        "blessings of enjoyment over fruits, fragrances, "
                        "and delicacies."
                    ),
                },
                {
                    "he": (
                        'ויכוין בכל ברכה וברכה שמברך '
                        'לשם שמים ולהשלמת המאה ברכות '
                        'שתיקן דוד המלך'
                    ),
                    "en": (
                        "And one should have intent with each and every "
                        "blessing that he recites, for the sake of Heaven "
                        "and for the completion of the one hundred blessings "
                        "that King David enacted."
                    ),
                },
            ],
        ),
    )


if __name__ == "__main__":
    data = get_sample_data()
    tex = generate_tex(data)

    output_path = Path(__file__).parent / "sa_output.tex"
    output_path.write_text(tex, encoding="utf-8")
    print(f"LaTeX written: {output_path}")

    compile_pdf(str(output_path))
